import sys
import math
import cmath

def calcW(n, N):
    assert n < N
    im = -((math.pi*2*n)/N)
    p = complex(0, im)
    c = cmath.exp(p)
    r = 128 + (c.real * 32)
    i = 128 + (c.imag * 32)
    return int(r),int(i)

def main(argv):
    if 2 != len(argv):
        print "Error: Args"
        return

    N = int(argv[1])

    print "// Autogenerated"
    print "#include \"fft8051.h\""
    print "static const complex_t W[N] = {"
    for j in range(N):
        r,i = calcW(j,N)
        print "\t{" + str(r) + "," + str(i) + "}",
        if j != N-1:
            print ",",
        print""
    print "}"


if "__main__" == __name__:
    main(sys.argv)

